version: 2
updates:
  # Enable version updates for Docker
  - package-ecosystem: "maven"
    # Look for a `pom.xml` in the `root` directory
    directory: "/"
    # Check for updates once a week
    schedule:
      interval: "daily"